### ISSUE TITLE
[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: sl-ember-components]

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1508]
When running `ember build` or `ember serve`.

This began appearing after the upgrade to Ember CLI 1.13.10 from 1.13.8.

Can be worked against the `v0.12.0` branch.  Will update this issue if further upgrades cause a change in status.

**Comment by juwara0** [comment]
Per https://github.com/ember-cli/ember-cli/issues/5092 the issue appears to be that `new this.Funnel()` needs to be changed to `new Funnel()`.

I have looked through our code base and I do not see any usage that we have in sl-ember-components that is not already updated.

Next step, is to look through the dependencies we control and see if they are updated correctly. After that once we bump our other dependencies we will be able to determine if the issue is fixed or still persists.

**Comment by notmessenger** [comment]
```
/sl-ember-components/node_modules/ember-cli/lib/models/addon.js:
  147  
  148  
  149:   this.Funnel = deprecatedAddonFilters(this, 'new this.Funnel(..)', 'broccoli-funnel', function(tree, options) {
  150      return new Funnel(tree, options);
  151    });
  ...
  403    }
  404  
  405:   return new this.Funnel(tree, {
  406      destDir: 'app/styles'
  407    });
```

**Comment by notmessenger** [comment]
Resolved in https://github.com/ember-cli/ember-cli/pull/5094, will be included in the https://github.com/softlayer/sl-ember-components/issues/1503 work.

**Comment by notmessenger** [comment]
Resolved by https://github.com/softlayer/sl-ember-components/issues/1503
