### ISSUE TITLE
application build fails if font-awesome already used by application

### ISSUE THREAD

**Issue by Twinkletoes** [softlayer/sl-ember-components#166]

**Comment by sparkrevolutions** [comment]
+1 to this

Received this error too today:
`Merge error: file fonts/fontawesome-webfont.woff exists in /Users/work/git/testproject/testproject/tmp/tree_merger-tmp_dest_dir-PhsNjgMh.tmp and /Users/work/git/testproject/testproject/tmp/static_compiler-tmp_dest_dir-joY7j0AM.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.`

Resolved by commit. Thank you very much @Twinkletoes

**Comment by notmessenger** [comment]
@Twinkletoes @sparkrevolutions Did you also use the overwrite: true option in your application's Brocfile.js?  I have been testing various combinations of this option in a consuming application and within this repo's index.js file (as per the pull request) and it seems to be the entry in the consuming application's Brocfile.js that fixes the reported issue.

I don't think it will cause any issue though if this pull request is accepted, regardless of your answer(s) to the question above.

**Comment by Twinkletoes** [comment]
No, my app brocfile is:
```
/* global require, module */

var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp();

// Use `app.import` to add additional libraries to the generated
// output files.
//
// If you need to use different assets in different
// environments, specify an object as the first parameter. That
// object's keys should be the environment name and the values
// should be the asset to use in that environment.
//
// If the library that you are including contains AMD or ES6
// modules that you would like to import into your application
// please specify an object with the list of modules as keys
// along with the exports of each module as its value.

module.exports = app.toTree();
```

**Comment by Twinkletoes** [comment]
Ah - but font awesome is coming in from ember-cli-font-awesome

Maybe you should add a dependency on ember-cli-font-awesome rather than importing FA directly?

**Comment by notmessenger** [comment]
@Twinkletoes We'll give some consideration to the idea of possibly using ember-cli-font-awesome.

I will go ahead and merge this pull request since it fixes the issues in your environment, which are legitimate, as well as it does not cause any issues when ember-cli-font-awesome (npm) is not used and fontawesome (bower) is used instead.

As an aside, 
https://github.com/lfridael/ember-cli-font-awesome#how-do-i-prevent-the-addon-from-including-font-awesome-assets and https://github.com/lfridael/ember-cli-font-awesome#including-font-awesome-in-your-app-using-bower recommend managing the Font Awesome assets yourself in a production application, which would bring the consuming application's Brocfile.js file into play and the use of the overwrite: true option.
