### ISSUE TITLE
"TypeError: select2.matcher is not a function" error being thrown in sl-select demo page

### ISSUE THREAD

**Issue by erangeles** [softlayer/sl-ember-components#433]
when clicked on the label/input field the select drop down results remain in "searching" mode. Nothing drop down menu items get rendered.

**Comment by erangeles** [comment]
issue #434 address this issue. closing.

**Comment by notmessenger** [comment]
What is the cause of this error?  Because none of the changes in https://github.com/softlayer/sl-ember-components/pull/434 jump out at me as being what fixes this, given that the demo at http://softlayer.github.io/sl-ember-components/#/demos/sl-select is from the release on February 24 and the code being changed in the PR has been effect since then with no changes to the related lines of code but now it's throwing this error?

**Comment by notmessenger** [comment]
@erangeles added an explanation at https://github.com/softlayer/sl-ember-components/pull/434#discussion_r35027336
