### ISSUE TITLE
Refactor usage of sinon

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#533]
Follow the pattern of importing it like in https://github.com/softlayer/sl-ember-behavior/blob/master/tests/unit/mixins/component-test.js (introduced in https://github.com/softlayer/sl-ember-behavior/pull/90 ) in any file currently using sinon not in the same manner.

Can likely also remove the entry for it in tests/.jshintrc

**Comment by erangeles** [comment]
@notmessenger taking this. only have another issue atm.

**Comment by notmessenger** [comment]
@erangeles When you are ready to submit your PR make sure that your changes include all of the merged commits that occurred after you began working on this issue, specifically making sure that any additional sinon calls are refactored as well.

**Comment by jonathandavidson** [comment]
Imports of the sinon module in tests require ember-sinon, (https://github.com/csantero/ember-sinon) so this is the only sinon package that should be included. I would recommend removing any \*sinon\* packages from bower.json and package.json and running a fresh `ember install ember-sinon` and running `npm prune && npm cache clean && npm install` and `bower prune && bower cache clean && bower install` to be sure all others are removed.

Also, any app.import's in Brocfile.js should be removed. After that, all of the tests should pass provided they are importing the `sinon` module rather than using it directly like `window.sinon`.

**Comment by erangeles** [comment]
@notmessenger PR, not sure why huboard not referencing it. https://github.com/softlayer/sl-ember-components/pull/541

**Comment by notmessenger** [comment]
Resolved by https://github.com/softlayer/sl-ember-components/pull/541
